exclude = [
  "http://localhost:*",
  "https://localhost:*",
  "http://127.0.0.1*",
  "https://127.0.0.1*",
  "https://*.vercel.app/_next/*"
]
accept = ["200..299","403"] # allow 403 for sites that block bots
max_redirects = 10
user_agent = "lychee-ci"
