[build]
  publish = "."
  command = "echo No build command needed"

[dev]
  command = "node server.js"
  port = 8888

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
