services:
  - type: web
    name: justice-dashboard
    env: node
    plan: free
    buildCommand: |
      npm install
      cd justice-server && npm install
      cd ../justice-dashboard && npm install && npm run build
      cp -r dist/* ../justice-server/public/
    startCommand: cd justice-server && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: SESSION_SECRET  
        generateValue: true
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        generateValue: true
    healthCheckPath: /api/health
