name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  frontend:
    name: Frontend (justice-dashboard)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: justice-dashboard
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: npm
          cache-dependency-path: justice-dashboard/package-lock.json
      - run: npm ci
      - run: npm test --if-present -- --ci --watchAll=false
      - run: npm run build --if-present

  backend:
    name: Backend (repo root if present)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            justice-server/package-lock.json

      - name: Install root deps
        run: npm ci

      - name: Install backend deps
        working-directory: justice-server
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm install; fi
        shell: bash

      - name: Start backend (background) with health check
        env:
          PORT: 3000
          NODE_ENV: test
        run: |
          node justice-server/server.js &
          pid=$!
          for i in {1..30}; do
            if curl -fsS http://127.0.0.1:3000/health >/dev/null 2>&1; then
              echo "Backend healthy."
              break
            fi
            sleep 1
            if [ $i -eq 30 ]; then
              echo "Backend failed to become healthy."
              kill $pid || true
              exit 1
            fi
          done

      - name: Run tests
        env:
          NODE_ENV: test
        run: npm test
        shell: bash

