name: node-core-tests

on:
  pull_request:
  push:
    branches:
      - main
      - feat/streaming-progress

permissions:
  contents: read

jobs:
  node-core:
    name: Node core tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.11.1'
          cache: 'pnpm'
      - name: Enable corepack (pnpm)
        run: corepack enable
      - name: Install
        run: pnpm -r install --frozen-lockfile
      - name: Run node core tests
        run: pnpm run test:unit-node
